development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: myapp_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: myapp_test
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: myapp_development
  username: root
  password:
